auth:
  callback:
    cookie:
      name: "TOKEN"
      domain: "localhost"
      path: "/"
      same-site: "Lax"
      max-age: 3600
      secure: false
      http-only: false
  jwt:
    token:
      issuer: "accounts.mzlnk.io"
      expiration-time: 3600
      public-key: "secrets/ids-key-v1.crt"
      private-key: "secrets/ids-key-v1.key"
  providers:
    GOOGLE:
      client-id: "XXXXX"
      client-secret: "XXXXX"
      redirect-uri: "http://localhost:8080/idb/api/v1/auth/callback/google"
      enabled: true
    GITHUB:
      client-id: "XXXXX"
      client-secret: "XXXXX"
      redirect-uri: "http://localhost:8080/idb/api/v1/auth/callback/github"
      enabled: true

server:
  port: 8080
